const games = [

{
id:1,
name:"11ABC Rummy",
slug:"11abc-rummy",
image:"images/11abcrummy.webp",
banner:"images/banners/11abcrummy.webp",
rating:"4.9",
downloads:"5M+",
bonus:"₹75",
withdraw:"₹100",
category:"Rummy",
featured:true,
trending:true,
latest:true,
description:"11ABC Rummy is a popular online rummy game with exciting welcome bonus and quick withdrawal.",
downloadUrl:"https://www.11abcrummy.com/?code=75CAZX4PBFD&t=1783424461",
page:"games/11abc-rummy.html"
},

{
id:2,
name:"Bet213",
slug:"bet213",
image:"images/bet213.webp",
banner:"images/banners/bet213.webp",
rating:"4.8",
downloads:"3M+",
bonus:"₹60",
withdraw:"₹100",
category:"Casino",
featured:true,
trending:false,
latest:true,
description:"Bet213 offers casino games, slots and daily rewards.",
downloadUrl:"https://www.bet213.pro/?code=2QTYVYTR77F&t=1783424494",
page:"games/bet213.html"
},

{
id:3,
name:"Bingo101",
slug:"bingo101",
image:"images/bingo101.webp",
banner:"images/banners/bingo101.webp",
rating:"4.9",
downloads:"4M+",
bonus:"₹90",
withdraw:"₹100",
category:"Bingo",
featured:true,
trending:true,
latest:false,
description:"Play Bingo101 and enjoy instant welcome bonus with exciting rewards.",
downloadUrl:"https://bingo-101.buzz/?code=H73SL4DYWJW&t=1783424530",
page:"games/bingo101.html"
},

{
id:4,
name:"Boss Rummy",
slug:"boss-rummy",
image:"images/bossrummy.webp",
banner:"images/banners/bossrummy.webp",
rating:"5.0",
downloads:"8M+",
bonus:"₹80",
withdraw:"₹100",
category:"Rummy",
featured:true,
trending:true,
latest:true,
description:"Boss Rummy provides secure gameplay with fast withdrawals.",
downloadUrl:"https://www.bossrummyo.com/?code=9HFAK694TXD&t=1783424563",
page:"games/boss-rummy.html"
},

{
id:5,
name:"Club INR",
slug:"club-inr",
image:"images/clubinr.webp",
banner:"images/banners/clubinr.webp",
rating:"4.8",
downloads:"2M+",
bonus:"₹55",
withdraw:"₹100",
category:"Casino",
featured:false,
trending:true,
latest:false,
description:"Club INR offers premium gaming experience with welcome rewards.",
downloadUrl:"https://clubinrvip.cc/?code=9VCJY3HUXKW&t=1783424610",
page:"games/club-inr.html"
},

{
id:6,
name:"Game Rummy",
slug:"game-rummy",
image:"images/gamerummy.webp",
banner:"images/banners/gamerummy.webp",
rating:"4.9",
downloads:"6M+",
bonus:"₹70",
withdraw:"₹100",
category:"Rummy",
featured:true,
trending:false,
latest:true,
description:"Game Rummy gives players exciting tournaments and bonus offers.",
downloadUrl:"https://gamerummyc.com/?code=Q6WD4YVGSKG&t=1783045708",
page:"games/game-rummy.html"
},

{
id:7,
name:"Go Spin",
slug:"go-spin",
image:"images/gospin.webp",
banner:"images/banners/gospin.webp",
rating:"5.0",
downloads:"10M+",
bonus:"₹100",
withdraw:"₹100",
category:"Slots",
featured:true,
trending:true,
latest:true,
description:"Go Spin is one of the most popular slot games with instant rewards.",
downloadUrl:"https://www.gospin.bet/?code=498S6EMARN5&t=1783045757",
page:"games/go-spin.html"
},

{
id:8,
name:"Hindi777",
slug:"hindi777",
image:"images/hindi777.webp",
banner:"images/banners/hindi777.webp",
rating:"4.9",
downloads:"7M+",
bonus:"₹65",
withdraw:"₹100",
category:"Casino",
featured:true,
trending:true,
latest:false,
description:"Hindi777 provides exciting games with trusted withdrawals.",
downloadUrl:"https://www.hindi777agent5.com/?code=7LFCL9PJ516&t=1783045793",
page:"games/hindi777.html"
},

{
id:9,
name:"Hi Rummy",
slug:"hi-rummy",
image:"images/hirummy.webp",
banner:"images/banners/hirummy.webp",
rating:"5.0",
downloads:"12M+",
bonus:"₹110",
withdraw:"₹100",
category:"Rummy",
featured:true,
trending:true,
latest:true,
description:"Hi Rummy offers premium online rummy experience and exciting bonuses.",
downloadUrl:"https://joinhirummy.cc/?code=RX3HPNUFL1W&t=1783045895",
page:"games/hi-rummy.html"
},

{
id:10,
name:"IND Club",
slug:"ind-club",
image:"images/indclub.webp",
banner:"images/banners/indclub.webp",
rating:"4.8",
downloads:"9M+",
bonus:"₹50",
withdraw:"₹100",
category:"Casino",
featured:false,
trending:true,
latest:true,
description:"IND Club features multiple casino games with welcome rewards.",
downloadUrl:"https://indclub36.com/?code=34UGAHJAEGU&t=1783045944",
page:"games/ind-club.html"
},
  {
id:11,
name:"IND Slots",
slug:"ind-slots",
image:"images/indslots.webp",
banner:"images/banners/indslots.webp",
rating:"4.9",
downloads:"8M+",
bonus:"₹85",
withdraw:"₹100",
category:"Slots",
featured:true,
trending:true,
latest:true,
description:"IND Slots offers exciting slot games with instant rewards.",
downloadUrl:"https://www.indslotsgame.com/?code=T2Q18VEZGLG&t=1783045984",
page:"games/ind-slots.html"
},

{
id:12,
name:"MQM Bet",
slug:"mqm-bet",
image:"images/mqm.webp",
banner:"images/banners/mqm.webp",
rating:"4.8",
downloads:"3M+",
bonus:"₹70",
withdraw:"₹100",
category:"Casino",
featured:false,
trending:false,
latest:true,
description:"MQM Bet provides multiple casino games and welcome rewards.",
downloadUrl:"https://6mqmshare.vip?pid=337905532&channel=2030000&pkg=com.mqmbet3001.app",
page:"games/mqm-bet.html"
},

{
id:13,
name:"INR Rummy",
slug:"inr-rummy",
image:"images/inrrummy.webp",
banner:"images/banners/inrrummy.webp",
rating:"4.9",
downloads:"6M+",
bonus:"₹95",
withdraw:"₹100",
category:"Rummy",
featured:true,
trending:true,
latest:false,
description:"Play INR Rummy with fast withdrawals and exciting tournaments.",
downloadUrl:"https://inrrummysvip2.net/?code=JMQKAVX7KWE&t=1783046109",
page:"games/inr-rummy.html"
},

{
id:14,
name:"JaiHo Arcade",
slug:"jaiho-arcade",
image:"images/jaihoarcade.webp",
banner:"images/banners/jaihoarcade.webp",
rating:"4.8",
downloads:"5M+",
bonus:"₹60",
withdraw:"₹100",
category:"Arcade",
featured:true,
trending:false,
latest:true,
description:"JaiHo Arcade features fun games and attractive rewards.",
downloadUrl:"https://www.jaihoarcade34.com/?code=AZDCZKW7BNV&t=1783046145",
page:"games/jaiho-arcade.html"
},

{
id:15,
name:"JaiHo Slots",
slug:"jaiho-slots",
image:"images/jaihoslots.webp",
banner:"images/banners/jaihoslots.webp",
rating:"4.9",
downloads:"7M+",
bonus:"₹90",
withdraw:"₹100",
category:"Slots",
featured:true,
trending:true,
latest:true,
description:"JaiHo Slots is one of the most popular slot games.",
downloadUrl:"https://www.jaihoslots18.com/?code=EGP7RY4XTDY&t=1783046174",
page:"games/jaiho-slots.html"
},

{
id:16,
name:"JaiHo Spin",
slug:"jaiho-spin",
image:"images/jaihospin.webp",
banner:"images/banners/jaihospin.webp",
rating:"4.9",
downloads:"5M+",
bonus:"₹55",
withdraw:"₹100",
category:"Slots",
featured:false,
trending:true,
latest:true,
description:"Spin daily and earn exciting rewards with JaiHo Spin.",
downloadUrl:"https://1jaihospinslot.com/?code=7TA6DT11LF3&t=1783046216",
page:"games/jaiho-spin.html"
},

{
id:17,
name:"JaiHo Win",
slug:"jaiho-win",
image:"images/jaihowin.webp",
banner:"images/banners/jaihowin.webp",
rating:"5.0",
downloads:"9M+",
bonus:"₹100",
withdraw:"₹100",
category:"Casino",
featured:true,
trending:true,
latest:true,
description:"JaiHo Win offers premium casino games and fast withdrawals.",
downloadUrl:"https://www.jaihowin16.com/?code=1XN5PLDRBGJ&t=1783046440",
page:"games/jaiho-win.html"
},

{
id:18,
name:"JaiHo777",
slug:"jaiho777",
image:"images/jaiho777.webp",
banner:"images/banners/jaiho777.webp",
rating:"4.9",
downloads:"8M+",
bonus:"₹80",
withdraw:"₹100",
category:"Casino",
featured:true,
trending:false,
latest:true,
description:"JaiHo777 gives exciting welcome bonuses and tournaments.",
downloadUrl:"https://jaiho77792.com/?code=GC2PL1RSXZD&t=1783046484",
page:"games/jaiho777.html"
},

{
id:19,
name:"91 JaiHo",
slug:"91-jaiho",
image:"images/91jaiho.webp",
banner:"images/banners/91jaiho.webp",
rating:"4.8",
downloads:"4M+",
bonus:"₹65",
withdraw:"₹100",
category:"Casino",
featured:false,
trending:true,
latest:false,
description:"91 JaiHo provides secure gaming with instant rewards.",
downloadUrl:"https://91jaihoapp.com/?code=C422BB6Y941&t=1783046532",
page:"games/91-jaiho.html"
},

{
id:20,
name:"Joy Rummy",
slug:"joy-rummy",
image:"images/joyrummy.webp",
banner:"images/banners/joyrummy.webp",
rating:"5.0",
downloads:"11M+",
bonus:"₹110",
withdraw:"₹100",
category:"Rummy",
featured:true,
trending:true,
latest:true,
description:"Joy Rummy is a premium online rummy platform with exciting bonuses.",
downloadUrl:"https://www.joyrummylux.com/?code=J5KY29TE89Q&t=1783046573",
page:"games/joy-rummy.html"
},
  {
id:21,
name:"Love Rummy",
slug:"love-rummy",
image:"images/loverummy.webp",
banner:"images/banners/loverummy.webp",
rating:"4.9",
downloads:"7M+",
bonus:"₹75",
withdraw:"₹100",
category:"Rummy",
featured:true,
trending:true,
latest:true,
description:"Love Rummy offers exciting tournaments and welcome rewards.",
downloadUrl:"https://www.loverummy1.com/?code=AFCJ9HGB44A&t=1783046624",
page:"games/love-rummy.html"
},

{
id:22,
name:"Maha Games",
slug:"maha-games",
image:"images/mahagames.webp",
banner:"images/banners/mahagames.webp",
rating:"4.8",
downloads:"5M+",
bonus:"₹60",
withdraw:"₹100",
category:"Casino",
featured:false,
trending:true,
latest:false,
description:"Maha Games provides multiple casino games with daily rewards.",
downloadUrl:"https://on-mahagames.com/?code=J24LM8HUX75&t=1783046672",
page:"games/maha-games.html"
},

{
id:23,
name:"MBM Bet",
slug:"mbm-bet",
image:"images/mbmbet.webp",
banner:"images/banners/mbmbet.webp",
rating:"4.9",
downloads:"6M+",
bonus:"₹95",
withdraw:"₹100",
category:"Casino",
featured:true,
trending:true,
latest:true,
description:"MBM Bet offers casino games with instant bonus.",
downloadUrl:"https://www.mbmbet28.com/?code=UPH8J9BHY9Q&t=1783046724",
page:"games/mbm-bet.html"
},

{
id:24,
name:"789 Jackpot",
slug:"789-jackpot",
image:"images/789jackpot.webp",
banner:"images/banners/789jackpot.webp",
rating:"5.0",
downloads:"9M+",
bonus:"₹110",
withdraw:"₹100",
category:"Slots",
featured:true,
trending:true,
latest:true,
description:"789 Jackpot offers premium slot games and rewards.",
downloadUrl:"https://join789jackpots1.com/?code=J7ZRKV1ELHS&t=1783046769",
page:"games/789-jackpot.html"
},

{
id:25,
name:"777OKOK",
slug:"777okok",
image:"images/777okok.webp",
banner:"images/banners/777okok.webp",
rating:"4.8",
downloads:"5M+",
bonus:"₹65",
withdraw:"₹100",
category:"Casino",
featured:false,
trending:true,
latest:false,
description:"777OKOK offers exciting online casino games.",
downloadUrl:"https://www.777okok.com/?code=H53V3D3M674&t=1783046815",
page:"games/777okok.html"
},

{
id:26,
name:"567 Slots",
slug:"567-slots",
image:"images/567slots.webp",
banner:"images/banners/567slots.webp",
rating:"4.9",
downloads:"7M+",
bonus:"₹80",
withdraw:"₹100",
category:"Slots",
featured:true,
trending:true,
latest:true,
description:"567 Slots features modern slot games with rewards.",
downloadUrl:"https://join567slots1.cc/?code=4NYYNGE217D&t=1783046875",
page:"games/567-slots.html"
},

{
id:27,
name:"Yono777",
slug:"yono777",
image:"images/yono777.webp",
banner:"images/banners/yono777.webp",
rating:"5.0",
downloads:"12M+",
bonus:"₹100",
withdraw:"₹100",
category:"Casino",
featured:true,
trending:true,
latest:true,
description:"Yono777 offers premium casino games and instant withdrawals.",
downloadUrl:"https://yono777hub.online/?code=F9MJTEWN4UX&t=1783047076",
page:"games/yono777.html"
},

{
id:28,
name:"Uono VIP",
slug:"uono-vip",
image:"images/uonovip.webp",
banner:"images/banners/uonovip.webp",
rating:"4.8",
downloads:"4M+",
bonus:"₹55",
withdraw:"₹100",
category:"Casino",
featured:false,
trending:false,
latest:true,
description:"Uono VIP provides daily bonuses and secure gameplay.",
downloadUrl:"https://uonovipfast.com/?code=3CRW27JYQQ9&t=1783047147",
page:"games/uono-vip.html"
},

{
id:29,
name:"Uono Slots",
slug:"uono-slots",
image:"images/uonoslots.webp",
banner:"images/banners/uonoslots.webp",
rating:"4.9",
downloads:"6M+",
bonus:"₹90",
withdraw:"₹100",
category:"Slots",
featured:true,
trending:true,
latest:false,
description:"Uono Slots is a trusted slot gaming platform.",
downloadUrl:"https://www.uonoslots.com/?code=59YKJDMVEZG&t=1783047209",
page:"games/uono-slots.html"
},

{
id:30,
name:"Yono Rummy",
slug:"yono-rummy",
image:"images/yonorummy.webp",
banner:"images/banners/yonorummy.webp",
rating:"5.0",
downloads:"10M+",
bonus:"₹105",
withdraw:"₹100",
category:"Rummy",
featured:true,
trending:true,
latest:true,
description:"Yono Rummy offers online rummy tournaments with exciting rewards.",
downloadUrl:"https://yonorummy047.com/?code=VIPYHS8XTPY&t=1783047280",
page:"games/yono-rummy.html"
},
  {
id:31,
name:"Yono Games",
slug:"yono-games",
image:"images/yonogames.webp",
banner:"images/banners/yonogames.webp",
rating:"4.9",
downloads:"8M+",
bonus:"₹85",
withdraw:"₹100",
category:"Casino",
featured:true,
trending:true,
latest:true,
description:"Play Yono Games with instant bonus and daily rewards.",
downloadUrl:"https://youonogamespromocode.com/?code=TC4QC28JKLM&t=1783047332",
page:"games/yono-games.html"
},

{
id:32,
name:"Yono Official",
slug:"yono-official",
image:"images/yonoofficial.webp",
banner:"images/banners/yonoofficial.webp",
rating:"5.0",
downloads:"12M+",
bonus:"₹110",
withdraw:"₹100",
category:"Casino",
featured:true,
trending:true,
latest:true,
description:"Official Yono platform with premium gaming experience.",
downloadUrl:"https://yonoofficial3.com/?code=GTSRBZZ32Z9&t=1783047379",
page:"games/yono-official.html"
},

{
id:33,
name:"Yes Spin",
slug:"yes-spin",
image:"images/yesspin.webp",
banner:"images/banners/yesspin.webp",
rating:"4.8",
downloads:"5M+",
bonus:"₹60",
withdraw:"₹100",
category:"Slots",
featured:false,
trending:true,
latest:false,
description:"Spin and win exciting rewards with Yes Spin.",
downloadUrl:"https://www.yesspinnow.com/?code=47TP7UQQ1PZ&t=1783047472",
page:"games/yes-spin.html"
},

{
id:34,
name:"Top Rummy",
slug:"top-rummy",
image:"images/toprummy.webp",
banner:"images/banners/toprummy.webp",
rating:"4.9",
downloads:"7M+",
bonus:"₹95",
withdraw:"₹100",
category:"Rummy",
featured:true,
trending:true,
latest:true,
description:"Top Rummy offers secure gameplay and fast withdrawal.",
downloadUrl:"https://www.toprummy.cc/?code=7K9LY1QFUJ5&t=1783047569",
page:"games/top-rummy.html"
},

{
id:35,
name:"Spin101",
slug:"spin101",
image:"images/spin101.webp",
banner:"images/banners/spin101.webp",
rating:"4.9",
downloads:"6M+",
bonus:"₹75",
withdraw:"₹100",
category:"Slots",
featured:true,
trending:false,
latest:true,
description:"Spin101 offers modern slot games and welcome rewards.",
downloadUrl:"https://spin101-c.net/?code=3X2GPDXYBEN&t=1783047712",
page:"games/spin101.html"
},

{
id:36,
name:"Spin777",
slug:"spin777",
image:"images/spin777.webp",
banner:"images/banners/spin777.webp",
rating:"4.8",
downloads:"5M+",
bonus:"₹70",
withdraw:"₹100",
category:"Slots",
featured:false,
trending:true,
latest:false,
description:"Spin777 is a popular slot game with daily rewards.",
downloadUrl:"https://spin777dd.com/?code=7V9SH1ZGF27&t=1783047786",
page:"games/spin777.html"
},

{
id:37,
name:"Spin Winner",
slug:"spin-winner",
image:"images/spinwinner.webp",
banner:"images/banners/spinwinner.webp",
rating:"5.0",
downloads:"10M+",
bonus:"₹100",
withdraw:"₹100",
category:"Slots",
featured:true,
trending:true,
latest:true,
description:"Spin Winner gives instant rewards and premium gameplay.",
downloadUrl:"https://spinwinner-g.com/?code=SDN6ZMNDX1U&t=1783047844",
page:"games/spin-winner.html"
},

{
id:38,
name:"Slots Spin",
slug:"slots-spin",
image:"images/slotsspin.webp",
banner:"images/banners/slotsspin.webp",
rating:"4.8",
downloads:"4M+",
bonus:"₹65",
withdraw:"₹100",
category:"Slots",
featured:false,
trending:false,
latest:true,
description:"Slots Spin offers classic slot gaming experience.",
downloadUrl:"https://slotsspinl.com/?code=XJBM7Y8QQQH&t=1783047986",
page:"games/slots-spin.html"
},

{
id:39,
name:"Share477",
slug:"share477",
image:"images/share477.webp",
banner:"images/banners/share477.webp",
rating:"4.9",
downloads:"6M+",
bonus:"₹80",
withdraw:"₹100",
category:"Casino",
featured:true,
trending:true,
latest:false,
description:"Share477 offers casino games with exciting rewards.",
downloadUrl:"https://share477.com/?code=YAZKHB26CGT&t=1783048024",
page:"games/share477.html"
},

{
id:40,
name:"Rumble Rummy",
slug:"rumble-rummy",
image:"images/rumblerummy.webp",
banner:"images/banners/rumblerummy.webp",
rating:"5.0",
downloads:"9M+",
bonus:"₹105",
withdraw:"₹100",
category:"Rummy",
featured:true,
trending:true,
latest:true,
description:"Rumble Rummy is a premium rummy platform with fast withdrawals.",
downloadUrl:"https://www.rumblerummy333.net/?code=UC0SU9FD5QX&t=1783048070",
page:"games/rumble-rummy.html"
},
  {
id:41,
name:"OK Rummy",
slug:"ok-rummy",
image:"images/okrummy.webp",
banner:"images/banners/okrummy.webp",
rating:"4.8",
downloads:"5M+",
bonus:"₹70",
withdraw:"₹100",
category:"Rummy",
featured:true,
trending:true,
latest:true,
description:"OK Rummy offers smooth gameplay with instant rewards.",
downloadUrl:"https://www.okrummy41.com/?code=H2GU19KMB2W&t=1783048126",
page:"games/ok-rummy.html"
},

{
id:42,
name:"Rummy77 Bonus",
slug:"rummy77-bonus",
image:"images/rummy77.webp",
banner:"images/banners/rummy77.webp",
rating:"4.9",
downloads:"7M+",
bonus:"₹95",
withdraw:"₹100",
category:"Rummy",
featured:true,
trending:false,
latest:true,
description:"Play Rummy77 and get exciting welcome rewards.",
downloadUrl:"https://rummy77bonus.net/?code=F3VJQX8LLY7&t=1783048174",
page:"games/rummy77-bonus.html"
},

{
id:43,
name:"Rummy888 VIP",
slug:"rummy888-vip",
image:"images/rummy888.webp",
banner:"images/banners/rummy888.webp",
rating:"5.0",
downloads:"9M+",
bonus:"₹110",
withdraw:"₹100",
category:"Rummy",
featured:true,
trending:true,
latest:true,
description:"Premium Rummy888 platform with instant withdrawal.",
downloadUrl:"https://rummy888vip38.com/?code=TPUQEBHBDCU&t=1783048215",
page:"games/rummy888-vip.html"
},

{
id:44,
name:"Rumm Ludo",
slug:"rumm-ludo",
image:"images/rummludo.webp",
banner:"images/banners/rummludo.webp",
rating:"4.8",
downloads:"4M+",
bonus:"₹60",
withdraw:"₹100",
category:"Ludo",
featured:false,
trending:true,
latest:false,
description:"Play Ludo and Rummy together with daily rewards.",
downloadUrl:"https://rummludo.com/?code=UWPWVG4MR7Y&t=1783048276",
page:"games/rumm-ludo.html"
},

{
id:45,
name:"Rummy91",
slug:"rummy91",
image:"images/rummy91.webp",
banner:"images/banners/rummy91.webp",
rating:"4.9",
downloads:"6M+",
bonus:"₹85",
withdraw:"₹100",
category:"Rummy",
featured:true,
trending:true,
latest:true,
description:"Rummy91 offers exciting tournaments and secure gameplay.",
downloadUrl:"https://www.rummy91r.bet/?code=CEELB9T658N&t=1783048317",
page:"games/rummy91.html"
},

{
id:46,
name:"Saga Slots",
slug:"saga-slots",
image:"images/sagaslots.webp",
banner:"images/banners/sagaslots.webp",
rating:"4.9",
downloads:"8M+",
bonus:"₹100",
withdraw:"₹100",
category:"Slots",
featured:true,
trending:true,
latest:true,
description:"Saga Slots provides modern slot games with instant bonus.",
downloadUrl:"https://www.sagaslots5.com/?code=41LV9QCX16B&t=1783048379",
page:"games/saga-slots.html"
},

{
id:47,
name:"Spin Gold",
slug:"spin-gold",
image:"images/spingold.webp",
banner:"images/banners/spingold.webp",
rating:"4.8",
downloads:"5M+",
bonus:"₹65",
withdraw:"₹100",
category:"Slots",
featured:false,
trending:true,
latest:false,
description:"Spin Gold lets you enjoy premium slot gaming.",
downloadUrl:"https://spingold4.com/?code=HLTSA9JQW5H&t=1783048464",
page:"games/spin-gold.html"
},

{
id:48,
name:"77 Game",
slug:"77-game",
image:"images/77game.webp",
banner:"images/banners/77game.webp",
rating:"5.0",
downloads:"10M+",
bonus:"₹110",
withdraw:"₹100",
category:"Casino",
featured:true,
trending:true,
latest:true,
description:"77 Game offers casino, slots and rummy games.",
downloadUrl:"https://77game.plus/?code=QGTT8ZS",
page:"games/77-game.html"
},

{
id:49,
name:"Good Slots",
slug:"good-slots",
image:"images/goodslots.webp",
banner:"images/banners/goodslots.webp",
rating:"4.9",
downloads:"7M+",
bonus:"₹80",
withdraw:"₹100",
category:"Slots",
featured:true,
trending:true,
latest:true,
description:"Good Slots is a modern slot gaming platform.",
downloadUrl:"https://4sharegoodslots.vip?pid=531453132&channel=2030111&pkg=com.goodslots111.com",
page:"games/good-slots.html"
},

{
id:50,
name:"Diwa Slots",
slug:"diwa-slots",
image:"images/diwaslots.webp",
banner:"images/banners/diwaslots.webp",
rating:"4.8",
downloads:"5M+",
bonus:"₹75",
withdraw:"₹100",
category:"Slots",
featured:true,
trending:false,
latest:true,
description:"Diwa Slots offers exciting rewards and premium slot games.",
downloadUrl:"https://sharediwaslots3.vip?pid=450275843&channel=2030101&pkg=com.diwaslot101.app",
page:"games/diwa-slots.html"
}

];
